### ISSUE TITLE
Is debian:bullseye-slim local image in debian.dockerfile file 

### ISSUE THREAD

**Issue by APIPLM** [lassik/pandoc-tar#1]
I tried to build a image by running` docker build . -t pandoc-tar`. The following error came out.
```
Sending build context to Docker daemon 2.048 kB
Step 1/8 : FROM debian:bullseye-slim AS build
Error parsing reference: "debian:bullseye-slim AS build" is not a valid repository/tag: invalid reference format
```

The error description sound like that docker can not find  repository `debian:bullseye-slim` from hub.docker.com. Is that repository in local docker repo.

**Comment by lassik** [comment]
That Debian is from the official Docker Hub, not a local repo. Are you using an old version of Docker?

**Comment by APIPLM** [comment]
The docker version in my side is in the following.
`Docker version 1.13.1, build 7d71120/1.13.1`

Does it matter with docker version? I will build a new docker exe.

**Comment by lassik** [comment]
I think we've been using Docker version 18. Version 1 is probably old enough that it doesn't support `FROM ... AS` syntax.

**Comment by APIPLM** [comment]
Thanks. It is building the docker now. Yes. The `debian:bullseye-slim` is tag `bullseye-slim `of `debian `image from hub.docker.com.
